/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e6e3cd",
        "surface-container": "#f2eed8",
        "secondary-fixed-dim": "#c8c8b0",
        "on-tertiary": "#ffffff",
        "secondary": "#5e604d",
        "on-secondary-container": "#636451",
        "on-primary": "#ffffff",
        "on-surface": "#1d1c0f",
        "surface": "#fefae4",
        "surface-dim": "#dedbc5",
        "tertiary": "#5d2c00",
        "surface-container-highest": "#e6e3cd",
        "tertiary-container": "#7f3f00",
        "primary-container": "#2d5a27",
        "outline-variant": "#c2c9bb",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#bcf0ae",
        "on-background": "#1d1c0f",
        "primary-fixed-dim": "#a1d494",
        "on-primary-container": "#9dd090",
        "on-error": "#ffffff",
        "secondary-container": "#e1e1c9",
        "on-tertiary-fixed-variant": "#713700",
        "inverse-surface": "#323122",
        "background": "#fefae4",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#474836",
        "inverse-on-surface": "#f5f1db",
        "on-primary-fixed-variant": "#23501e",
        "surface-container-high": "#ece9d3",
        "surface-tint": "#3b6934",
        "secondary-fixed": "#e4e4cc",
        "inverse-primary": "#a1d494",
        "surface-bright": "#fefae4",
        "tertiary-fixed": "#ffdcc5",
        "on-tertiary-fixed": "#301400",
        "on-primary-fixed": "#002201",
        "on-surface-variant": "#42493e",
        "tertiary-fixed-dim": "#ffb783",
        "on-tertiary-container": "#ffb27a",
        "outline": "#72796e",
        "error": "#ba1a1a",
        "primary": "#154212",
        "surface-container-low": "#f8f4de",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#1b1d0e",
        "on-secondary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
};
